spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/flowboard
        username: postgres
        password: postgres

    jpa:
        hibernate:
            ddl-auto: validate
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
